name: GitHub Activity Automation

on:
  schedule:
    - cron: "0 1 * * *" # Runs daily at 1 AM UTC, 8 PM EST
  workflow_dispatch: # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }} # Use the token for authentication

      - name: Modify file
        run: |
          echo "$(date)" >> activity.log

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "ravi-rajpurohit-gh"
          git config --global user.email "ravirajpurohit414@gmail.com"
          git add activity.log
          git commit -m "Automated commit on $(date)" || exit 0  # Avoid failure if no changes
          git push
